name: Trigger auto deployment for activepieces

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ prod ]
    paths:
    - 'docker/images/n8n/**'
    - '.github/workflows/activepieces-AutoDeployTrigger-db6d5c8e-d72a-41ee-af79-038557564489.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACTIVEPIECES_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/docker/images/n8n 
          registryUrl: handler.azurecr.io
          registryUsername: ${{ secrets.ACTIVEPIECES_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACTIVEPIECES_REGISTRY_PASSWORD }}
          containerAppName: activepieces
          resourceGroup: chatlog
          imageToBuild: handler.azurecr.io/n8n:${{ github.sha }}
          
            

     

