name: Docker Image CI

on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ prod ]
    paths:
    - 'docker/images/n8n/**'
    - '.github/workflows/activepieces-AutoDeployTrigger-db6d5c8e-d72a-41ee-af79-038557564489.yml'

  # Allow manual trigger 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:14})

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACTIVEPIECES_AZURE_CREDENTIALS }}

      - name: Build
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./docker/images/n8n
          build-args: |
            N8N_VERSION=${{ steps.vars.outputs.tag }}
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          tags: |
            handler.azurecr.io/n8n:${{ github.sha }}
